backend:
  name: git-gateway
  branch: master

media_folder: "src/images"

collections:
  - label: Home Employees
    name: home-employees
    folder: cms/home/employees
    create: false
    fields:
      - {label: Name, name: title, widget: string}
      - {label: Body, name: body, widget: markdown}
