backend:
  name: git-gateway
  branch: master
media_folder: "src/images"
collections:
  - name: "home"
    label: "Hem"
    files:
      - file: "src/cms/home/introduction.md"
        label: "Introduktion"
        name: "introduction"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
